

name: nginx:alpine

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.SECRET_USER }}
          password: ${{ secrets.SECRET_BUILD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.SECRET_USER }}/app:latest
